### ISSUE TITLE
file error with a 400MB zip

### ISSUE THREAD

**Issue by FortNbreak** [riolubruh/SplitLargeFiles#10]
yea. it says "Your Files are too powerful" "The max file size for nitro classic is 50MB"
i am trying to upload a zip that is 400 MB

edit by riolubruh: remove screenshot (contains user's ip address)
edit 2: upload cropped/censored screenshot 
![image](https://github.com/riolubruh/SplitLargeFiles/assets/54255074/e3e9d0fc-17fd-4cc2-a19c-3c06f5a59c96)

**Comment by FortNbreak** [comment]
is there a cap to how big of a file can upload with this plugin?

**Comment by riolubruh** [comment]
> is there a cap to how big of a file can upload with this plugin?

Technically, there isn't, though it will start to bug out >1.5gb because of technical reasons, and there is a limit of 255 chunks.. Also, you should be more careful of what you screenshot, your IP address was right there!?

**Comment by riolubruh** [comment]
I have replicated the issue and am currently working on resolving it.

**Comment by riolubruh** [comment]
Fixed

**Comment by Eject37** [comment]
It still doesn't work for me, is there any way I can help fix the problem?
![27-11-2023 14_17_34](https://github.com/riolubruh/SplitLargeFiles/assets/57284098/10c05771-d0ff-490b-8fde-a3dfd63652b8)
![27-11-2023 14_17_43](https://github.com/riolubruh/SplitLargeFiles/assets/57284098/48da70e3-6cf9-407d-9ef0-320a440a63e2)

**Comment by FortNbreak** [comment]
it allows me to upload the chunks but never reconstructs it visually even if all are uploaded

also my fault on leaking my ip lmao

**Comment by riolubruh** [comment]
> it never reconstructs it visually even if all are uploaded

this issue is known about, I don't know how to fix it since I don't really understand how to fix ImTheSquid's code for that part.
I managed to partially fix it, so uploaded files should appear like this (image),
![](https://github.com/riolubruh/SplitLargeFiles/assets/54255074/cd9848af-2c4d-49db-8310-df42a2df9ede)
(only the first chunk appears visually)
but it's still not correct.
It's the reason why **there's a button in the right-click menu to download the chunks,** which is currently the intended way to download and reassemble the chunks.

**Comment by riolubruh** [comment]
Bumping this issue.

@FortNbreak ?
